name: CI

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["1.6", "1.12"]
    name: build LearningHorse
    steps:
      - uses: actions/checkout@v7
      - name: Set up Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v3
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1
      - name: Run Test
        uses: julia-actions/julia-runtest@v1
      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
